Add configuration support for nyhoor websocket read limit
improbable-eng/grpc-web pull request #1023
Opened 2021-07-08 21:14 UTC by bryanmcgrane

Adding support to configure the underlying nyhoor websocket read limit.

## Changes

The changes are minimal

1. Add new configuration property `WithWebsocketsMessageReadLimit`
2. Apply this read limit to the websocket if it is configured, otherwise do nothing. In this case the default limit is used.

## Verification

The codes successfully builds and works in my local environment.

2021-07-08 21:32 UTC, bryanmcgrane commented
FYI - the build failed due to changes outside of my PR. It looks like the go.mod file has some linting issues.

2021-07-09 02:43 UTC, johanbrandhorst requested changes
Hi, thanks for this change! I think it's missing an additional flag for the grpcwebproxy standalone proxy that could configure this setting for the standalone proxy. What do you think?

2021-07-09 14:59 UTC, bryanmcgrane commented
Good thinking. That change has been made as well!

2021-07-10 19:35 UTC, johanbrandhorst commented
Looks like CI is failing because of some module inconsistencies. Could you run `go mod tidy` and commit the changes?

2021-07-10 19:35 UTC, johanbrandhorst approved these changes
Scratch that, I don't see why this change should cause any import changes.

2021-07-10 19:36 UTC, merged

2021-07-10 19:36 UTC, johanbrandhorst commented
Thanks for your contribution!

2021-07-12 16:46 UTC, bryanmcgrane commented
You're welcome1