Fix /metrics, /debug/requests, /debug/events + additional flag for enabling those
improbable-eng/grpc-web pull request #957
Opened 2021-04-27 10:16 UTC by zolkin

/metrics and /debug/*  was not working in the several latest releases. I restored the functionality and added a flag to enable those

## Changes
- /metrics , /debug/requests, /debug/events manually added to the http debug server.
- 

## Verification

Manual testing weas performend to check that new handlers do not interfere with grpc request processing with websockets enabled and disabled. /debug/* pages were checked to be accessible only from localhost if enabled, /metrics is accessible from everywhere if enabled.

2021-04-27 12:50 UTC, johanbrandhorst reviewed
Thanks for this!

2021-04-27 12:50 UTC, johanbrandhorst commented on go/grpcwebproxy/main.go
> +			}
This is great, but what do you think about making it a switch statement instead? It's a bit more Go-like:
```suggestion
			switch req.URL.Path {
			case "/metrics":
				metricsHandler.ServeHTTP(resp, req)
			case "/debug/requests":
				trace.Traces(resp, req)
			case "/debug/events":
				trace.Events(resp, req)
			default:
				wrappedGrpc.ServeHTTP(resp, req)
			}
```

2021-04-27 13:12 UTC, zolkin commented
Thanks for quick reply and code change suggestions.

2021-04-27 13:14 UTC, johanbrandhorst requested changes
Please fix the flag comment, otherwise this looks good to go :)

2021-04-27 13:14 UTC, johanbrandhorst commented on go/grpcwebproxy/main.go
> +	enableRequestDebug = pflag.Bool("enable_request_debug", false, "whether to enable (/debug/requests) and connection(/debug/events) monitoring; also controls prometheus monitoring (/monitoring)")
Just realised this looks wrong as well, sorry I missed it.
```suggestion
	enableRequestDebug = pflag.Bool("enable_request_debug", false, "whether to enable (/debug/requests) and connection(/debug/events) monitoring; also controls prometheus monitoring (/metrics)")
```

2021-04-27 13:20 UTC, johanbrandhorst approved these changes
LGTM

2021-04-27 13:27 UTC, johanbrandhorst commented
CI tests look like saucelab errors (CC @MarcusLongmuir):
```
+ (( ++wait_seconds ))
+ echo 'Timed out waiting for sauce labs tunnel (with ssl bump)'
+ kill 1359
./run-with-tunnel.sh: line 93: kill: (1359) - No such process
+ killTunnels
62.390566 Timed out waiting for sauce labs tunnel (with ssl bump)
+ echo 'Killing Sauce Labs Tunnels...'
+ [[ -z '' ]]
+ kill 1359
62.390631 Killing Sauce Labs Tunnels...
./run-with-tunnel.sh: line 79: kill: (1359) - No such process
npm ERR! code 1
npm ERR! path /go/src/github.com/improbable-eng/grpc-web/integration_test
npm ERR! command failed
npm ERR! command sh -c ./run-with-tunnel.sh ./run-with-testserver.sh karma start ./karma.conf.ts --single-run
```

2021-06-30 00:14 UTC, johanbrandhorst commented
I'm rerunning the tests again.

2021-06-30 00:33 UTC, johanbrandhorst commented
Failed again, but I dare say it's unrelated to this change so I'm going to go ahead and merge.

2021-06-30 00:33 UTC, merged